# Generated by Django 4.2.2 on 2023-06-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='full_name',
            field=models.CharField(default=None, max_length=127),
            preserve_default=False,
        ),
    ]
