# Generated by Django 4.2.2 on 2023-07-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='perfil',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
