# Generated by Django 4.2.2 on 2023-07-03 19:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_rename_seguidor_follower_follower_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='friends',
        ),
        migrations.AddField(
            model_name='user',
            name='friend_solicitations',
            field=models.ManyToManyField(related_name='solicitacao_amizade', through='usuarios.Friend', to=settings.AUTH_USER_MODEL),
        ),
    ]
