# Generated by Django 4.2.2 on 2023-06-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='image',
            field=models.CharField(max_length=180, null=True),
        ),
        migrations.AlterField(
            model_name='publication',
            name='text',
            field=models.CharField(max_length=2500),
        ),
    ]
