# Generated by Django 4.2.2 on 2023-07-03 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0003_publication_image_alter_publication_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
