# Generated by Django 4.2.2 on 2023-07-03 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publicacoes', '0004_publication_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='public',
            field=models.BooleanField(),
        ),
    ]
