# Generated by Django 4.2.2 on 2023-07-06 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('publicacoes', '0001_initial'),
        ('curtidas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='like',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publication_like', to='publicacoes.publication'),
        ),
    ]
